### ISSUE TITLE
Headless Mode Doesn't Support PDF Rendering

### ISSUE THREAD

**Issue by thiscantbetaken** [mdn/headless-examples#5]
I have a requirement to navigate to a PDF URL in Firefox Headless and then enter a search term, but for some reason the PDF never gets loaded or rendered with a screenshot.

Even attempting to use an external JavaScript library to embed a PDF doesn't work.

firefox -headless -screenshot https://www.epa.gov/sites/production/files/2017-12/documents/lcr_federalism_consultation_letter.signed.12_14_17.pdf
firefox -headless -screenshot https://mozilla.github.io/pdf.js/web/viewer.html

Are there any options via Selenium or perhaps with an external PDF viewer that can be used in conjunction with Headless Firefox, to open a PDF URL and then enter a search phrase?

**Comment by chrisdavidmills** [comment]
@mykmelez — have you got any idea how this could be done? Thanks!

**Comment by mykmelez** [comment]
cc: @brendandahl, who has worked on both headless and pdf.js, for his thoughts.

**Comment by brendandahl** [comment]
I haven't looked into this too deeply, but I assume firefox is snapshotting the page way before the PDF is loaded since pdf.js loads an html page before it starts rendering the PDF. 

Using Selenium/WebDriver should work to screenshot the PDF. SlimerJS should also work too.

**Comment by thiscantbetaken** [comment]
I am using the Selenium Webdriver, and triggering on elements found in the
JavaScript PDF viewer followed by a five second pause to make sure the
snapshot takes place. So I don't think it's the delay.

**Comment by brendandahl** [comment]
What shows in the screenshot?

**Comment by thiscantbetaken** [comment]
Just a black box, nothing is rendered at all.
