### ISSUE TITLE
TypeError: firefox.Binary is not a constructor

### ISSUE THREAD

**Issue by yehgdotnet** [mdn/headless-examples#6]
Any idea?

```
$ node selenium-test.js
/selenium/selenium-test.js:7
var binary = new firefox.Binary(firefox.Channel.NIGHTLY);
             ^

TypeError: firefox.Binary is not a constructor
    at Object.<anonymous> (/selenium/selenium-test.js:7:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
```

**Comment by mightytyphoon** [comment]
same problem, I tried a lot of workarounds, with geckodriver, nothing is working

```
var webdriver = require('selenium-webdriver')
var By = webdriver.By
var until = webdriver.until
var promise = webdriver.promise

var firefox = require('selenium-webdriver/firefox')
var binary = require('selenium-binaries').geckodriver
    //var binary = new firefox.Binary('C:/Program Files/Mozilla Firefox/firefox.exe')
    //binary.addArguments("-headless")

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(new firefox.Options().setBinary(binary))
    .build()

driver.then( () => {
  driver.get('https://www.google.com')
} , 
  (error) => {
    console.log(error)
  })
```

> { WebDriverError: Process unexpectedly closed with status 1
>     at Object.throwDecodedError (C:\Users\Maison\projects\tests\headless-browser\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\Maison\projects\tests\headless-browser\node_modules\selenium-webdriver\lib\http.js:542:13)
>     at Executor.execute (C:\Users\Maison\projects\tests\headless-browser\node_modules\selenium-webdriver\lib\http.js:468:26)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:182:7) name: 'WebDriverError', remoteStacktrace: '' }

**Comment by chrisdavidmills** [comment]
hi folks, 

Apologies for taking so long to respond to this.

Have you both tried running the exact code found at https://github.com/mdn/headless-examples/blob/master/selenium-test.js?

I've just tried it, and it works for me. If you can't run this code, then there must be some other difference that is causing problems? What OSes are you running your code on?

**Comment by randymartinez** [comment]
Hey I'm having the same issue. I ran the test code and still receive the same error. Currently I am running on Kali linux. 

Node v8.9.3
Selenium v4.0.0-alpha.1
Firefox v61.0.1

**Comment by rrfaria** [comment]
I also have the same issues

**Comment by randymartinez** [comment]
``var webdriver = require('selenium-webdriver'),
	By = webdriver.By,
	until = webdriver.until;

const firefox = require('selenium-webdriver/firefox');
const fs = require('fs');

require('geckodriver');

async function capture(url) {
  var path = '/root/firefox/firefox-bin';
  var args = '-headless';

  const driver = new webdriver.Builder()
	.forBrowser('firefox')
	.setFirefoxOptions(new firefox.Options().setBinary(path).addArguments(args))
	.build()

  await driver.get(url);
  const data = await driver.takeScreenshot();
  fs.writeFileSync('./screenshot.png', data, 'base64');

  driver.quit();
}

capture('https://hacks.mozilla.org/');
``

I created a test script using a guide found on the mozilla website. This ran correctly for me. https://developer.mozilla.org/en-US/Firefox/Headless_mode

**Comment by chrisdavidmills** [comment]
I couldn't get that script to run. But the original I wrote still works fine. I just set it all up again on a new machine and tested it again.

Maybe ask the engineers for some help if you are still having trouble: https://developer.mozilla.org/en-US/Firefox/Headless_mode#Troubleshooting_and_further_help ?

**Comment by hugovila** [comment]
It is possible that the error is due to the used version of selenium. 
In version 4, something like:

var binary = new firefox.Binary(firefox.Channel.NIGHTLY);
must be changed to:
var options = new firefox.Options().setBinary(firefox.Channel.NIGHTLY);

later you can add some options:
options.addArguments("--headless");

and finally: 
const driver = new Builder()
  .forBrowser('firefox')
  .setFirefoxOptions(options)
  .build();


For me that has worked.
I have collected that information from: ./node_modules/selenium-webdriver/firefox.js

**Comment by twiclo** [comment]
When I try @hugovila's solution I end up with TypeError: firefox.Options is not a constructor

```var webdriver = require('selenium-webdriver')
var firefox = require('geckodriver')
var options = new firefox.Options()
options.addArguments("--headless")

const driver =  new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build()```

**Comment by twiclo** [comment]
@hugovila when you ran that how did you install geckodriver? I've just been using the geckodriver npm package but when I try your options it tells me geckodriver isn't in my path

**Comment by chrisdavidmills** [comment]
Hi everyone. I've finally found time to come back to this issue.

So, I tried out the new syntax, and got it working:

https://github.com/mdn/headless-examples/blob/master/selenium-test.js

I also updated the MDN article as appropriate:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode

I think this is simpler now we don;'t need to specify Nightly anymore (it's been supported in release for about 9 versions now ;-))

**Comment by chrisdavidmills** [comment]
Let me know if this works for you.

**Comment by lumenier1** [comment]
> Let me know if this works for you.

Doesn't work for me:

```
(node:79741) UnhandledPromiseRejectionWarning: NoSuchSessionError: Tried to run command without establishing a connection
    at Object.throwDecodedError (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:655:13)
    at Executor.execute (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:581:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:79741) UnhandledPromiseRejectionWarning: NoSuchSessionError: Tried to run command without establishing a connection
    at Object.throwDecodedError (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:655:13)
    at Executor.execute (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:581:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:79741) UnhandledPromiseRejectionWarning: NoSuchSessionError: Tried to run command without establishing a connection
    at Object.throwDecodedError (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:655:13)
    at Executor.execute (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:581:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:79741) UnhandledPromiseRejectionWarning: NoSuchSessionError: Tried to run command without establishing a connection
    at Object.throwDecodedError (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:655:13)
    at Executor.execute (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:581:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:79741) UnhandledPromiseRejectionWarning: NoSuchSessionError: Tried to run command without establishing a connection
    at Object.throwDecodedError (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:655:13)
    at Executor.execute (/Users/Bob/Documents/Selenium/node/node_modules/selenium-webdriver/lib/http.js:581:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

```
